### ISSUE TITLE
where does object.writeTo('/path/to/destination') move the data too?

### ISSUE THREAD

**Issue by gtrossell** [SpectraLogic/ds3_script#50]
While testing, I used the, object.writeTo command to write to ~/ but nothing happened. 

Can you please explain how this command works? Is it suppose to write to object to another bucket or download it to the local host.

Thanks

**Comment by sage-t** [comment]
object.writeTo will download the object to your computer's directory that you specify. If you did `object.writeTo('~/')` that would create a directory called '~' in your working directory and write the object there because bpsh currently doesn't understand the `~` character.

@rpmoore should we support `~` ?

**Comment by sage-t** [comment]
`~` will now reference the user's home directory 👍
